Repository techitPlus-FE-team3/open_market_projerct, pull requests merged in 2023-11, with the labels that each got.

#4 :sparkles: [Feat] 라우터 기능 추가 #3
  open-market/src/routes.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#5 ✨ [Feat] 라우터 기능 추가 #3
  open-market/src/App.tsx
  open-market/src/pages/Index.tsx
  open-market/src/routes.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#8 :lipstick:[Design] Login 페이지 마크업 작업 및 라우트 연결 #2
  open-market/src/pages/Login.tsx
  open-market/src/routes.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#7 [Feature] 폰트어썸 material UI 세팅 #1
  open-market/package-lock.json
  open-market/package.json
Labels: merge 요청

#10 ✨ [Feature] 라우터에 RootLayout 생성 및 연결, 💄 [Design] 메인페이지 마크업 작업 #3
  open-market/src/layout/RootLayout.tsx
  open-market/src/pages/Index.tsx
  open-market/src/routes.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#12 💄[Design] SignUp 페이지 마크업 작업 및 라우트 추가, 연결 #9
  open-market/src/pages/Login.tsx
  open-market/src/pages/SignUp.tsx
  open-market/src/routes.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#13 ✨[Feat] 폰트어썸 material UI 세팅 #1
  open-market/package-lock.json
  open-market/package.json
Labels: 검토 요청 (이상 없으면 Merge)

#14 💄 [Design] 상품등록 페이지 마크업 작업 #11
  open-market/src/pages/ProductRegistration.tsx
  open-market/src/routes.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#15 🚚[Rename] Login을 SignIn으로 수정 #2
  open-market/src/pages/SignIn.tsx
  open-market/src/routes.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#18 💄 [Design] 상품 상세 페이지 마크업 작업 #6
  open-market/package-lock.json
  open-market/src/pages/Detail.tsx
  open-market/src/routes.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#19 :lipstick: [Design] 상품 수정 페이지 마크업 #16
  open-market/src/pages/Index.tsx
  open-market/src/pages/ProductUpdate.tsx
  open-market/src/routes.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#21 🚚 [Rename] ProductUpdate 컴포넌트명 수정 #16
  open-market/src/pages/Index.tsx
  open-market/src/pages/ProductEdit.tsx
  open-market/src/routes.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#22 💄[Design] 회원정보수정 페이지 마크업 및 라우트 추가 #17
  open-market/src/pages/UserUpdate.tsx
  open-market/src/routes.tsx
Labels: 검토중

#23 💄 [Design] 상품등록 페이지 레이아웃 변경 #11
  open-market/src/pages/ProductRegistration.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#25 💄 [Design] 헤더/푸터 요소 배치 #20
  open-market/src/layout/Footer.tsx
  open-market/src/layout/Header.tsx
  open-market/src/layout/RootLayout.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#27 :lipstick: [Design] 구매 페이지 마크업 #26
  open-market/src/pages/Purchase.tsx
  open-market/src/routes.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#28 Design/header footer
  open-market/src/layout/Header.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#30 :lipstick: [Design] 상품 관리 페이지 마크업
  open-market/src/pages/ProductManage.tsx
  open-market/src/routes.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#33 💄 [Design] 헤더, 푸터 마크업 + 임시 스타일링 #20
  open-market/package-lock.json
Labels: 검토 요청 (이상 없으면 Merge)

#34 💄 [Design] 마이페이지 마크업#31
  open-market/src/pages/MyPage.tsx
  open-market/src/routes.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#36 💄[Design] 판매상품 관리 페이지 마크업 #24
  open-market/src/pages/UserProducts.tsx
  open-market/src/routes.tsx
Labels: merge 요청

#37 💄 [Design] 공통 속성지정 및 스타일링 설정
  open-market/index.html
  open-market/src/App.tsx
  open-market/src/styles/common.ts
Labels: 검토 요청 (이상 없으면 Merge)

#38 💄[Design] 구매내역 페이지 마크업 및 라우트 추가 #35
  open-market/src/pages/UserOrders.tsx
  open-market/src/routes.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#45 💄 [Design] 구매페이지 마크업 수정#42
  open-market/src/pages/Purchase.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#46 [Design] 피그마 디자인에 맞게 로그인 페이지 마크업 수정 #44
  open-market/src/pages/SignIn.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#50 💄 [Design] 상품 구매 페이지 음원 업로드 마크업 추가, 레이아웃 변경 #49
  open-market/src/pages/ProductRegistration.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#55 💄 [Design] 상품 구매 페이지 label 부분 마크업 수정 #49
  open-market/src/pages/ProductRegistration.tsx
  open-market/src/routes.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#56 [Design] 구매 내역 페이지 마크업 수정 #54
  open-market/src/pages/UserOrders.tsx
  open-market/src/routes.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#58 💄 [Design] 상품 상세 페이지 마크업 수정 #57
  open-market/src/pages/Detail.tsx
  open-market/src/pages/MyPage.tsx
  open-market/src/routes.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#60 💄 [Design] 상품 수정 페이지 마크업 수정 #59
  open-market/src/pages/ProductEdit.tsx
  open-market/src/routes.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#64 💄[Design] 헤더 태그 수정 및 푸터 정리 #61
  open-market/src/layout/Footer.tsx
  open-market/src/layout/Header.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#67 💄[Design] 회원 정보 수정 페이지 마크업 수정 #66
  open-market/src/pages/UserUpdate.tsx
  open-market/src/routes.tsx
Labels: 검토중

#65 🐛 [Fix] 마이페이지 부적절한 태그 등 수정 #68
  open-market/src/pages/MyPage.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#75 💄[Design] 헤더 로고 이미지 추가#74
  open-market/src/layout/Header.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#73 ✅ [Feat] 회원가입 기능 구현 #71
  open-market/src/App.tsx
  open-market/src/pages/SignUp.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#77 ✨[Feature] 전체 프로덕트 리스트 조회 기능 구현 #70
  open-market/public/noImage.svg
  open-market/src/pages/Index.tsx
  open-market/src/product.d.ts
  open-market/src/routes.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#79 ✨ [Feat] 로그인 기능 구현 #76
  open-market/index.html
  open-market/src/pages/SignIn.tsx
  open-market/src/pages/SignUp.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#83 ✨[Feature] 상품 상세 조회 기능 구현 #78
  open-market/src/pages/Detail.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#86 🐛 [Fix] 회원가입 시 구체적인 메시지 표시가 안되는 문제 및 전화번호 입력칸 기능 추가.
  open-market/src/pages/SignUp.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#88 ✨ [Feat] 상품 등록 기능 구현 #72
  open-market/package-lock.json
  open-market/src/pages/ProductRegistration.tsx
  open-market/src/utils/uploadFile.ts
Labels: 검토 요청 (이상 없으면 Merge)

#89 ✨ [Feat] 토큰 리프레시 기능 구현 #85
  open-market/src/pages/MyPage.tsx
  open-market/src/utils/TokenRefresh.ts
Labels: 검토 요청 (이상 없으면 Merge)

#91 ✨[Feat] 장르 데이터 배열 생성 #90
  open-market/src/data/genres.ts
Labels: 검토 요청 (이상 없으면 Merge)

#94 ✨[Feat] 회원가입 단계에서 이메일 중복 확인 기능 구현 #93
  open-market/src/pages/SignUp.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#96 ✨ [Feat] 상품 등록기능 구현 #95
  open-market/src/pages/ProductRegistration.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#97 ✨ [Feature] 상품 삭제 기능 구현
  open-market/src/pages/ProductManage.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#98 ✨[Feature] 상품 구매 기능 구현 #84
  open-market/src/order.d.ts
  open-market/src/pages/Detail.tsx
  open-market/src/pages/Purchase.tsx
  open-market/src/product.d.ts
  open-market/src/routes.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#101 ✨[Feat] 마이페이지 북마크된 상품 표시 기능 구현 #82
  open-market/src/pages/MyPage.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#103 💄 [Design] 알림 react-hot-toast로 변경 #102
  open-market/src/pages/SignIn.tsx
  open-market/src/pages/SignUp.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#104 ✨ [Feature] 내 판매 상품 조회 기능 구현 #100
  open-market/src/pages/MyPage.tsx
  open-market/src/pages/UserProducts.tsx
  open-market/src/routes.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#106 ✨ [Feature] 내 판매 상품 리스트 조회기능 구현
  open-market/src/pages/UserProducts.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#107 ✨ [Feature] 상품 삭제 기능 구현
  open-market/src/pages/MyPage.tsx
  open-market/src/pages/ProductManage.tsx
  open-market/src/pages/UserProducts.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#109 🐛 [Fix] 이미지 저장 경로 수정 #108
  open-market/src/pages/ProductRegistration.tsx
  open-market/src/utils/uploadFile.ts
Labels: 검토중

#113 ✨[Feat] 로그인 상태에서는 헤더의 로그인 / 회원가입 버튼이 마이페이지 버튼으로 바뀌게끔 기능 구현 #112
  open-market/src/App.tsx
  open-market/src/layout/Header.tsx
  open-market/src/main.tsx
  open-market/src/pages/SignIn.tsx
  open-market/src/states/authState.ts
Labels: 검토 요청 (이상 없으면 Merge)

#115 :sparkles: [Feature] 상품 수정 기능 구현 #111
  open-market/src/pages/ProductEdit.tsx
Labels: 검토중

#116 🐛 [Fix] 사진 두번 올라가는 버그 수정
  open-market/src/pages/ProductRegistration.tsx
Labels: 검토중

#117 ✨[Feat] Axios response interceptor 를 이용한 토큰 갱신 기능 개선 #114
  open-market/src/utils/TokenRefresh.ts
Labels: 검토 요청 (이상 없으면 Merge)

#120 ✨[Feat] 로그아웃 기능 생성
  open-market/src/layout/Header.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#122 ✨[Feature] 상품 구매 시 user order 수정 및 타입 변경 #99
  open-market/src/order.d.ts
  open-market/src/pages/Detail.tsx
  open-market/src/pages/Purchase.tsx
  open-market/src/product.d.ts
  open-market/src/user.d.ts
Labels: 검토 요청 (이상 없으면 Merge)

#124 🚀 [Deploy] 중간 발표를 위한 병합
  open-market/.eslintrc.cjs
  open-market/.gitignore
  open-market/.prettierrc
  open-market/index.html
  open-market/package-lock.json
  open-market/package.json
  open-market/public/logo/favicon.svg
  open-market/public/logo/logo1.svg
  open-market/public/logo/logo2.svg
  open-market/public/noImage.svg
  open-market/public/user.svg
  open-market/public/vite.svg
  open-market/src/App.css
  open-market/src/App.tsx
  open-market/src/custom.d.ts
  open-market/src/data/genres.ts
  open-market/src/index.css
  open-market/src/layout/Footer.tsx
  open-market/src/layout/Header.tsx
  open-market/src/layout/RootLayout.tsx
  open-market/src/main.tsx
  open-market/src/order.d.ts
  open-market/src/pages/Detail.tsx
  open-market/src/pages/Index.tsx
  open-market/src/pages/MyPage.tsx
  open-market/src/pages/ProductEdit.tsx
  open-market/src/pages/ProductManage.tsx
  open-market/src/pages/ProductRegistration.tsx
  open-market/src/pages/Purchase.tsx
  open-market/src/pages/SignIn.tsx
  open-market/src/pages/SignUp.tsx
  open-market/src/pages/UserOrders.tsx
  open-market/src/pages/UserProducts.tsx
  open-market/src/pages/UserUpdate.tsx
  open-market/src/product.d.ts
  open-market/src/routes.tsx
  open-market/src/states/authState.ts
  open-market/src/styles/common.ts
  open-market/src/user.d.ts
  open-market/src/utils/TokenRefresh.ts
  open-market/src/utils/uploadFile.ts
  open-market/src/vite-env.d.ts
  open-market/tsconfig.json
  open-market/tsconfig.node.json
  open-market/vite.config.ts
  samples/dbinit.js
Labels: merge 요청
