Repository techitPlus-FE-team3/open_market_projerct, pull requests merged in 2023-12, with the labels that each got.

#127 🐛[Fix] 상세 페이지 링크 수정 및 카테고리 추가 #78
  open-market/src/pages/Detail.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#129 ✨ [Feature] 삭제 후 직전 경로로 이동 하는기능 구현
  open-market/src/pages/ProductManage.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#130 🐛[Fix] 유저 상태에 따라 구매하기 버튼이 제대로 나오지 않는 문제 해결 #78
  open-market/src/pages/Detail.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#131 ✨[Feature] 구매한 상품에 후기 등록 기능 구현 #99
  open-market/src/pages/Detail.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#132 🎨[Style] 미사용 변수 _로 수정 및 미사용 컴포넌트 삭제 #99
  open-market/src/pages/Detail.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#135 ✅ [Test] order -> buyQuantity 수정
  samples/dbinit.js
Labels: 검토 요청 (이상 없으면 Merge)

#138 ✨ [Feature] 상품 입력 양식 미충족시 토스트 알람 팝업 기능 구현 #137
  open-market/src/pages/ProductRegistration.tsx
Labels: 검토중

#141 ✨ [Feature] order 관련 코드 수정 #136
  open-market/src/pages/Detail.tsx
  open-market/src/pages/Purchase.tsx
  open-market/src/user.d.ts
Labels: 검토 요청 (이상 없으면 Merge)

#145 🐛 [Fix] 헤더 로고 이미지 로딩 전 헤더 렌더링 완료시 엑박 문제 #144
  open-market/package-lock.json
  open-market/package.json
  open-market/src/layout/Header.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#154 🏷️[Type] API 변경에 맞게 인터페이스 수정 #153
  open-market/src/order.d.ts
  open-market/src/product.d.ts
Labels: 검토 요청 (이상 없으면 Merge)

#156 ♻️[Refactor] 폴더 구조 변경 및 정리, 컴포넌트 이름 변경 #155
  README.md
  open-market/src/App.css
  open-market/src/api/instance.ts
  open-market/src/data/genres.ts
  open-market/src/index.css
  open-market/src/interfaces/custom.d.ts
  open-market/src/interfaces/order.d.ts
  open-market/src/interfaces/product.d.ts
  open-market/src/interfaces/user.d.ts
  open-market/src/main.tsx
  open-market/src/pages/Index.tsx
  open-market/src/pages/product/ProductDetail.tsx
  open-market/src/pages/product/ProductEdit.tsx
  open-market/src/pages/product/ProductManage.tsx
  open-market/src/pages/product/ProductRegistration.tsx
  open-market/src/pages/product/Productpurchase.tsx
  open-market/src/pages/user/MyPage.tsx
  open-market/src/pages/user/SignIn.tsx
  open-market/src/pages/user/SignUp.tsx
  open-market/src/pages/user/UserEdit.tsx
  open-market/src/pages/user/UserOrders.tsx
  open-market/src/pages/user/UserProducts.tsx
  open-market/src/routes.tsx
  open-market/src/utils/refreshToken.ts
  open-market/tsconfig.json
Labels: 검토 요청 (이상 없으면 Merge)

#159 🐛[Fix] 타입 수정으로 발생한 오류 해결 #158
  open-market/src/interfaces/user.d.ts
  open-market/src/pages/product/ProductDetail.tsx
  open-market/src/pages/product/ProductEdit.tsx
  open-market/src/pages/product/ProductRegistration.tsx
  open-market/src/pages/user/UserProducts.tsx
  samples/dbinit.js
Labels: bug fix

#162 :sparkles: [Feature] debounce 함수 적용 #157
  open-market/src/pages/product/ProductDetail.tsx
  open-market/src/pages/product/ProductEdit.tsx
  open-market/src/pages/product/ProductRegistration.tsx
  open-market/src/pages/user/SignIn.tsx
  open-market/src/pages/user/SignUp.tsx
  open-market/src/utils/debounce.ts
  open-market/src/utils/index.ts
Labels: merge 요청, 검토 요청 (이상 없으면 Merge)

#163 ♻️[Refactor] 페이지 이동 방법 수정 #150
  open-market/src/pages/Index.tsx
  open-market/src/pages/product/ProductDetail.tsx
  open-market/src/pages/product/ProductRegistration.tsx
  open-market/src/pages/product/Productpurchase.tsx
  open-market/src/pages/user/MyPage.tsx
  open-market/src/routes.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#164 ✅ [Test] 테스트 데이터 수정
  samples/dbinit.js
Labels: 검토 요청 (이상 없으면 Merge)

#165 🐛[Fix] 비로그인 시 product detail에서 401 에러 발생 해결 #160
  open-market/src/pages/product/ProductDetail.tsx
Labels: bug fix

#167 ✅ [Test] 테스트 데이터 수정
  samples/dbinit.js
Labels: merge 요청

#169 ♻️[Refactor] axios를 axiosInstance로 수정 #166
  open-market/src/pages/Index.tsx
  open-market/src/pages/product/ProductDetail.tsx
  open-market/src/pages/product/Productpurchase.tsx
Labels: 검토 요청 (이상 없으면 Merge), non-critical

#173 :recycle:[Refactor] Productpurchase 파스칼케이스로 수정 및 user updtate url 수정 #155
  open-market/src/pages/product/Productpurchase.tsx
  open-market/src/routes.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#177 🐛[Fix] api 변경으로 인한 MyPage에서 bookmark 호출 코드 수정 #161
  open-market/src/pages/user/MyPage.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#178 ✨ [Feature] 상품리스트를 수익순으로 정렬하는 기능 구현 #172
  open-market/src/pages/user/UserProducts.tsx
  open-market/src/utils/index.ts
  open-market/src/utils/itemWithExpireTime.ts
  open-market/src/utils/numberWithComma.ts
  samples/dbinit.js
Labels: 검토 요청 (이상 없으면 Merge)

#182 :truck:[Rename] searchKeword를 searchKeyword로 수정 #181
  open-market/src/pages/Index.tsx
  open-market/src/utils/filterProductList.ts
Labels: merge 요청, 검토 요청 (이상 없으면 Merge)

#191 ✨[Feature] 헤더 검색 기능 구현 #176
  open-market/src/layout/Header.tsx
  open-market/src/main.tsx
  open-market/src/pages/Index.tsx
  open-market/src/states/productListState.ts
Labels: 검토 요청 (이상 없으면 Merge)

#192 ♻️[Refactor] 상품 등록시 앨범 이미지 required 속성으로 변경, 관련 코드들 수정 #174
  open-market/public/noImage.svg
  open-market/src/pages/Index.tsx
  open-market/src/pages/product/ProductDetail.tsx
  open-market/src/pages/product/ProductEdit.tsx
  open-market/src/pages/product/ProductRegistration.tsx
  open-market/src/pages/user/MyPage.tsx
  open-market/src/pages/user/UserOrders.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#194 ✨ [Feature] 카테고리(장르) 불러오는 기능 구현
  open-market/src/interfaces/category.d.ts
  open-market/src/pages/product/ProductEdit.tsx
  open-market/src/pages/product/ProductRegistration.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#196 ✨[Feature] url로 접근 불가능한 페이지의 접근 방지 #186
  open-market/src/pages/product/ProductEdit.tsx
  open-market/src/pages/product/ProductManage.tsx
  open-market/src/pages/product/ProductRegistration.tsx
  open-market/src/pages/product/Productpurchase.tsx
  open-market/src/pages/user/MyPage.tsx
  open-market/src/pages/user/SignUp.tsx
  open-market/src/pages/user/UserEdit.tsx
  open-market/src/pages/user/UserOrders.tsx
  open-market/src/pages/user/UserProducts.tsx
  open-market/src/utils/refreshToken.ts
Labels: 검토 요청 (이상 없으면 Merge)

#198 📦 [Chore] 코드 주석 제거 및 미리보기 추가 #196
  open-market/src/pages/user/MyPage.tsx
  open-market/src/pages/user/SignUp.tsx
Labels: merge 요청

#200 ✨[Feature] index 페이지 카테고리 필터 기능 구현 #193
  open-market/src/layout/Header.tsx
  open-market/src/pages/Index.tsx
  open-market/src/pages/product/ProductEdit.tsx
  open-market/src/pages/product/ProductRegistration.tsx
  open-market/src/states/productListState.ts
  open-market/src/utils/filterProductList.ts
Labels: 검토 요청 (이상 없으면 Merge)

#201 ✨ [Feature] 히스토리 기능 구현 #195
  open-market/src/pages/product/ProductDetail.tsx
  open-market/src/pages/user/MyPage.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#209 ✨[Feature] 카테고리 관련 코드 value 수정 #205
  open-market/src/layout/Header.tsx
  open-market/src/pages/Index.tsx
  open-market/src/pages/product/ProductDetail.tsx
  open-market/src/pages/product/ProductEdit.tsx
  open-market/src/pages/product/ProductRegistration.tsx
  open-market/src/utils/TokenRefresh.ts
  open-market/src/utils/filterProductList.ts
Labels: 검토 요청 (이상 없으면 Merge), non-critical

#213 ♻️[Refactor] API 수정에 따른 mainImages 타입 및 코드 수정 #212
  open-market/src/interfaces/order.d.ts
  open-market/src/interfaces/product.d.ts
  open-market/src/pages/Index.tsx
  open-market/src/pages/product/ProductDetail.tsx
  open-market/src/pages/product/ProductManage.tsx
  open-market/src/pages/product/ProductPurchase.tsx
  open-market/src/pages/user/MyPage.tsx
  open-market/src/pages/user/UserOrders.tsx
  open-market/src/pages/user/UserProducts.tsx
  open-market/src/utils/filterProductList.ts
Labels: 검토 요청 (이상 없으면 Merge), non-critical

#215 :sparkles:[Feature] 음원 다운로드 기능 구현 #202
  open-market/src/pages/product/ProductDetail.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#217 :recycle: [Refactor] api 수정에 따른 코드 수정 #211
  open-market/src/pages/product/ProductEdit.tsx
  open-market/src/pages/product/ProductRegistration.tsx
  open-market/src/utils/uploadFile.ts
  samples/dbinit.js
Labels: 검토 요청 (이상 없으면 Merge)

#219 🎨[Design] 로그인, 회원가입 페이지 스타일링 #214
  open-market/src/components/AuthInput.tsx
  open-market/src/layout/AuthLayout.tsx
  open-market/src/layout/RootLayout.tsx
  open-market/src/pages/user/SignIn.tsx
  open-market/src/pages/user/SignUp.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#222 🐛 [Fix] defaultChecked로 했을 때 checked 상태가 변경되지 않는 버그 수정
  open-market/src/components/FormInput.tsx
  open-market/src/components/FunctionalButton.tsx
  open-market/src/components/SelectGenre.tsx
  open-market/src/pages/product/ProductEdit.tsx
  open-market/src/pages/product/ProductRegistration.tsx
  open-market/src/utils/uploadFile.ts
Labels: 검토중

#223 💄[Design] 상품 리스트 컴포넌트 생성 및 스타일링 #216
  open-market/src/components/ProductListItem.tsx
  open-market/src/components/listMusicPlayer/ControlPanel.tsx
  open-market/src/components/listMusicPlayer/MusicPlayer.tsx
  open-market/src/components/listMusicPlayer/PlayerSlider.tsx
  open-market/src/interfaces/order.d.ts
  open-market/src/pages/Index.tsx
  open-market/src/pages/user/UserOrders.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#225 ♻️[Refactor] 마이페이지 북마크, 히스토리, 구매내역, 판매 상품 관리 공통 사용 사용 컴포넌트 구성 및 스타일링 #220
  open-market/src/components/MyPageList.tsx
  open-market/src/pages/user/MyPage.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#227 💄 [Design] 상품등록페이지 레이아웃 및 스타일링 #218
  open-market/src/components/FormInput.tsx
  open-market/src/components/FunctionalButton.tsx
  open-market/src/components/SelectGenre.tsx
  open-market/src/components/Textarea.tsx
  open-market/src/pages/product/ProductRegistration.tsx
  open-market/src/styles/common.ts
  open-market/src/utils/uploadFile.ts
Labels: 검토 요청 (이상 없으면 Merge)

#229 💄 [Design] 상품 수정 페이지 레이아웃 구성 및 스타일링 #228
  open-market/src/pages/product/ProductEdit.tsx
  open-market/src/pages/product/ProductRegistration.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#231 💄[Deisgn] searchbar, filter 컴포넌트 생성 및 스타일링 #224
  open-market/src/components/FilterComponent.tsx
  open-market/src/components/SearchBar.tsx
  open-market/src/interfaces/order.d.ts
  open-market/src/pages/Index.tsx
  open-market/src/pages/user/UserOrders.tsx
  open-market/src/pages/user/UserProducts.tsx
  open-market/src/utils/filterProductList.ts
  open-market/src/utils/itemWithExpireTime.ts
Labels: 검토 요청 (이상 없으면 Merge)

#233 💄[Design] 헤더 및 푸터 스타일링 #226
  open-market/src/layout/Footer.tsx
  open-market/src/layout/Header.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#234 💄 [Design] 상품관리 페이지 레이아웃 구성 및 스타일링 #230
  open-market/src/components/Textarea.tsx
  open-market/src/pages/product/ProductDetail.tsx
  open-market/src/pages/product/ProductManage.tsx
  open-market/src/pages/product/ProductRegistration.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#237 🐛[Fix] hover 시 전체 영역에 밑줄이 생기는 버그 해결 #235
  open-market/src/layout/Footer.tsx
  open-market/src/layout/Header.tsx
Labels: 검토 요청 (이상 없으면 Merge), bug fix

#238 💄[Design] 구매내역 페이지 스타일 작업 #232
  open-market/src/components/FilterComponent.tsx
  open-market/src/components/ProductListComponent.tsx
  open-market/src/components/ProductListItem.tsx
  open-market/src/components/SearchBar.tsx
  open-market/src/components/listMusicPlayer/ControlPanel.tsx
  open-market/src/components/listMusicPlayer/MusicPlayer.tsx
  open-market/src/components/listMusicPlayer/PlayerSlider.tsx
  open-market/src/pages/user/UserOrders.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#240 💄[Design] 인덱스 페이지 스타일 작업 #239
  open-market/public/banner.svg
  open-market/src/components/FilterComponent.tsx
  open-market/src/components/ProductListComponent.tsx
  open-market/src/components/SearchBar.tsx
  open-market/src/pages/Index.tsx
  open-market/src/pages/user/UserOrders.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#244 💄[Design] 판매 상품 관리 페이지 스타일 작업 #241
  open-market/src/components/FilterComponent.tsx
  open-market/src/components/ProductListItem.tsx
  open-market/src/components/SearchBar.tsx
  open-market/src/components/listMusicPlayer/ControlPanel.tsx
  open-market/src/components/listMusicPlayer/MusicPlayer.tsx
  open-market/src/components/listMusicPlayer/PlayerSlider.tsx
  open-market/src/pages/Index.tsx
  open-market/src/pages/user/UserOrders.tsx
  open-market/src/pages/user/UserProducts.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#245 💄 [Design] 상품 구매 페이지 레이아웃 구성 및 스타일링e #236
  open-market/src/components/FormInput.tsx
  open-market/src/components/Textarea.tsx
  open-market/src/pages/product/ProductManage.tsx
  open-market/src/pages/product/ProductPurchase.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#247 ♻️[Refactor] API 변경에 따른 db 수정 및 파일 경로 수정 #243
  open-market/src/components/ProductListItem.tsx
  open-market/src/pages/product/ProductDetail.tsx
  samples/dbinit.js
Labels: 검토 요청 (이상 없으면 Merge), non-critical

#248 💄[Design] 회원정보 수정 페이지 스타일링 #242
  open-market/src/components/AuthInput.tsx
  open-market/src/layout/RootLayout.tsx
  open-market/src/pages/user/MyPage.tsx
  open-market/src/pages/user/SignUp.tsx
  open-market/src/pages/user/UserEdit.tsx
  open-market/src/routes.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#249 :bug: [Fix] ProductListItem unique key error 수정 #221
  open-market/src/components/ProductListItem.tsx
Labels: bug fix

#251 🐛[Fix] 컨벤션에 따른 헤더 컴포넌트 함수 선언식으로 수정
  open-market/src/layout/Header.tsx
Labels: bug fix

#254 💄[Design] 댓글 컴포넌트 생성 및 스타일 작업 #246
  open-market/src/components/ReplyComponent.tsx
  open-market/src/pages/product/ProductDetail.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#257 🐛 [Fix] api 변경에 따른 파일 깨짐 수정 #256
  open-market/src/components/ProductListItem.tsx
  open-market/src/interfaces/product.d.ts
  open-market/src/pages/product/ProductDetail.tsx
  open-market/src/pages/product/ProductEdit.tsx
  open-market/src/pages/product/ProductManage.tsx
  open-market/src/pages/product/ProductPurchase.tsx
  open-market/src/pages/product/ProductRegistration.tsx
  open-market/src/pages/user/MyPage.tsx
  open-market/src/utils/uploadFile.ts
Labels: 검토 요청 (이상 없으면 Merge)

#258 💄[Design] 디테일 페이지 스타일 작업
  open-market/src/components/ProductDetailBadgeComponent.tsx
  open-market/src/components/ProductDetailComponent.tsx
  open-market/src/components/ReplyComponent.tsx
  open-market/src/pages/product/ProductDetail.tsx
  open-market/src/utils/numberWithComma.ts
Labels: 검토 요청 (이상 없으면 Merge)

#262 ♻️ [Refactor] 세부 사항 리팩토링 #250
  open-market/src/components/ReplyComponent.tsx
  open-market/src/components/SearchBar.tsx
  open-market/src/interfaces/product.d.ts
  open-market/src/layout/Header.tsx
  open-market/src/pages/Index.tsx
  open-market/src/pages/product/ProductPurchase.tsx
  open-market/src/pages/product/ProductRegistration.tsx
  open-market/src/pages/user/UserEdit.tsx
  open-market/src/pages/user/UserProducts.tsx
  open-market/src/states/productListState.ts
  open-market/src/utils/filterProductList.ts
Labels: 검토 요청 (이상 없으면 Merge)

#267 :recycle:[Refactor] 배포 후 뮤직 플레이어 에러 및 상품 등록/수정 시 파일 업로드 상태에 따라 로딩 스피너 표기 #259
  open-market/public/loadingSpinner.svg
  open-market/src/components/ProductListItem.tsx
  open-market/src/components/UploadLoadingSpinner.tsx
  open-market/src/components/listMusicPlayer/MusicPlayer.tsx
  open-market/src/interfaces/product.d.ts
  open-market/src/pages/product/ProductEdit.tsx
  open-market/src/pages/product/ProductRegistration.tsx
  open-market/src/utils/uploadFile.ts
Labels: bug, 검토 요청 (이상 없으면 Merge), non-critical

#268 :bug:[Fix] useRef TextArea 타입 에러 해결 #246 #252
  open-market/src/pages/product/ProductDetail.tsx
Labels: bug fix

#270 디테일 페이지 & 판매상품 관리 리팩토링 #253 #269
  open-market/index.html
  open-market/src/components/ProductDetailBadgeComponent.tsx
  open-market/src/components/ProductDetailComponent.tsx
  open-market/src/components/ReplyComponent.tsx
  open-market/src/interfaces/product.d.ts
  open-market/src/pages/product/ProductDetail.tsx
  open-market/src/pages/product/ProductManage.tsx
  open-market/src/pages/product/ProductRegistration.tsx
  open-market/src/utils/formData.ts
  open-market/src/utils/index.ts
Labels: 검토 요청 (이상 없으면 Merge), non-critical

#274 ♻️[Refactor] 마이페이지 컴포넌트 리액트 쿼리 도입 및 MUI 스켈레톤 적용 #264, #263
  open-market/package-lock.json
  open-market/package.json
  open-market/src/App.tsx
  open-market/src/layout/Header.tsx
  open-market/src/pages/user/MyPage.tsx
  open-market/src/pages/user/SignUp.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#278 💄[Design] 헤더 스타일 변경 및 페이지 레이아웃 스타일링 변경 #276
  open-market/index.html
  open-market/src/components/MyPageList.tsx
  open-market/src/components/ProductDetailComponent.tsx
  open-market/src/components/ProductListComponent.tsx
  open-market/src/layout/Header.tsx
  open-market/src/pages/Index.tsx
  open-market/src/pages/product/ProductDetail.tsx
  open-market/src/pages/product/ProductEdit.tsx
  open-market/src/pages/product/ProductManage.tsx
  open-market/src/pages/product/ProductPurchase.tsx
  open-market/src/pages/product/ProductRegistration.tsx
  open-market/src/pages/user/MyPage.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#279 ✨ [Feature] useInfinityQuery를 사용하여 무한 스크롤 구현 #266
  open-market/package-lock.json
  open-market/package.json
  open-market/src/App.tsx
  open-market/src/hooks/useCategoryFilterProductList.ts
  open-market/src/layout/Header.tsx
  open-market/src/pages/Index.tsx
  open-market/src/pages/user/UserOrders.tsx
  open-market/src/pages/user/UserProducts.tsx
  open-market/src/states/productListState.ts
  open-market/src/utils/filterProductList.ts
Labels: 검토 요청 (이상 없으면 Merge)

#280 ♻️[Refactor] 상품 구매 페이지 리팩토링 #272
  open-market/src/components/ProductDetailBadgeComponent.tsx
  open-market/src/components/ProductListItem.tsx
  open-market/src/components/listMusicPlayer/MusicPlayer.tsx
  open-market/src/pages/product/ProductDetail.tsx
  open-market/src/pages/product/ProductPurchase.tsx
Labels: non-critical

#282 ♻️[Refactor] 메인 페이지 리액트 쿼리 도입 시도 #275
  open-market/src/pages/Index.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#285 ♻️ [Refactor] reply 관련 로직 수정 #281
  open-market/package-lock.json
  open-market/package.json
  open-market/src/components/ReplyComponent.tsx
  open-market/src/pages/product/ProductDetail.tsx
  open-market/src/pages/user/UserEdit.tsx
Labels: non-critical

#286 ♻️[Refactor] 토큰 갱신 유틸(axiosInstance) 공통 헤더 설정 #284
  open-market/src/pages/product/ProductDetail.tsx
  open-market/src/pages/product/ProductEdit.tsx
  open-market/src/pages/product/ProductManage.tsx
  open-market/src/pages/product/ProductPurchase.tsx
  open-market/src/pages/product/ProductRegistration.tsx
  open-market/src/pages/user/MyPage.tsx
  open-market/src/pages/user/UserEdit.tsx
  open-market/src/pages/user/UserOrders.tsx
  open-market/src/pages/user/UserProducts.tsx
  open-market/src/utils/refreshToken.ts
  open-market/src/utils/uploadFile.ts
Labels: 검토중

#288 💄[Design] 로그인, 회원가입, 유저 정보 수정 페이지 최상단 태그 패딩 조정 #283
  open-market/src/pages/user/SignIn.tsx
  open-market/src/pages/user/SignUp.tsx
  open-market/src/pages/user/UserEdit.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#289 ♻️ [Refactor] 세부 리팩토링 #287 #283
  open-market/src/components/ProductListItem.tsx
  open-market/src/components/ReplyComponent.tsx
  open-market/src/hooks/useRequireAuth.ts
  open-market/src/layout/Header.tsx
  open-market/src/pages/product/ProductDetail.tsx
  open-market/src/pages/product/ProductEdit.tsx
  open-market/src/pages/product/ProductManage.tsx
  open-market/src/pages/product/ProductPurchase.tsx
  open-market/src/pages/product/ProductRegistration.tsx
  open-market/src/pages/user/SignIn.tsx
  open-market/src/pages/user/SignUp.tsx
  open-market/src/pages/user/UserEdit.tsx
  open-market/src/utils/refreshToken.ts
  open-market/src/utils/uploadFile.ts
Labels: 검토 요청 (이상 없으면 Merge), non-critical

#293 💄[Design] 회원가입, 유저정보 수정 페이지 레이아웃 깨짐 수정 #292
  open-market/.env
  open-market/src/pages/Index.tsx
  open-market/src/pages/product/ProductDetail.tsx
  open-market/src/pages/product/ProductEdit.tsx
  open-market/src/pages/product/ProductManage.tsx
  open-market/src/pages/product/ProductPurchase.tsx
  open-market/src/pages/product/ProductRegistration.tsx
  open-market/src/pages/user/SignIn.tsx
  open-market/src/pages/user/SignUp.tsx
  open-market/src/pages/user/UserEdit.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#294 ♻️ [Refactor] 추가 페이지 작업 #290
  open-market/src/components/AuthInput.tsx
  open-market/src/components/FunctionalButton.tsx
  open-market/src/components/MyPageList.tsx
  open-market/src/components/ProductDetailBadgeComponent.tsx
  open-market/src/components/ProductDetailComponent.tsx
  open-market/src/components/ProductListIComponent.tsx
  open-market/src/components/listMusicPlayer/MusicPlayer.tsx
  open-market/src/components/listMusicPlayer/PlayerSlider.tsx
  open-market/src/interfaces/product.d.ts
  open-market/src/layout/Footer.tsx
  open-market/src/layout/Header.tsx
  open-market/src/pages/Index.tsx
  open-market/src/pages/product/ProductDetail.tsx
  open-market/src/pages/product/ProductEdit.tsx
  open-market/src/pages/product/ProductManage.tsx
  open-market/src/pages/product/ProductPurchase.tsx
  open-market/src/pages/product/ProductRegistration.tsx
  open-market/src/pages/user/MyPage.tsx
  open-market/src/pages/user/SignIn.tsx
  open-market/src/pages/user/SignUp.tsx
  open-market/src/pages/user/UserEdit.tsx
  open-market/src/pages/user/UserOrders.tsx
  open-market/src/pages/user/UserProducts.tsx
  open-market/src/styles/ProductListStyle.tsx
  open-market/src/styles/common.ts
  open-market/src/utils/itemWithExpireTime.ts
  open-market/src/utils/refreshToken.ts
  open-market/src/utils/uploadFile.ts
Labels: 검토 요청 (이상 없으면 Merge), non-critical, bug fix

#296 📝[Docs] Update README.md
  README.md
Labels: merge 요청, non-critical

#298 📝[Docs] README.md 로컬 수정 #297
  README.md
  samples/teamates/asj.png
  samples/teamates/kbk.png
  samples/teamates/kjj.png
Labels: merge 요청, documentation, non-critical

#300 ♻️ [Refactor] 상품 등록/수정 시 content 영역 placeholder 추가
  open-market/src/components/Textarea.tsx
  open-market/src/pages/product/ProductEdit.tsx
  open-market/src/pages/product/ProductRegistration.tsx
Labels: 검토 요청 (이상 없으면 Merge), non-critical

#299 ✅[Test]토큰 갱신 기능 오류 해결을 위한 테스트 코드 #271
  open-market/src/utils/refreshToken.ts
Labels: bug, 검토중
