Repository techitPlus-FE-team3/open_market_projerct, pull requests merged in 2024-05, with the labels that each got.

#378 🐛 [Fix] 토큰 갱신 기능 에러 해결 #375
  open-market/package-lock.json
  open-market/package.json
  open-market/src/pages/user/MyPage.tsx
  open-market/src/pages/user/SignIn.tsx
  open-market/src/pages/user/UserEdit.tsx
  open-market/src/states/productListState.ts
  open-market/src/utils/refreshToken.ts
Labels: 검토 요청 (이상 없으면 Merge), bug fix

#380 ♻️ [Refactor] axiosInstance 분리 후 리액트 쿼리로 변경
  open-market/src/apis/product/order.ts
  open-market/src/apis/product/product.ts
  open-market/src/apis/user/bookMarks.ts
  open-market/src/apis/user/product.ts
  open-market/src/hooks/product/mutations/delete.ts
  open-market/src/hooks/product/mutations/edit.ts
  open-market/src/hooks/product/mutations/registration.ts
  open-market/src/hooks/product/queries/detail.ts
  open-market/src/hooks/product/queries/order.ts
  open-market/src/hooks/user/queries/bookMark.ts
  open-market/src/hooks/user/queries/detail.ts
  open-market/src/pages/product/ProductDetail.tsx
  open-market/src/pages/product/ProductEdit.tsx
  open-market/src/pages/product/ProductManage.tsx
  open-market/src/pages/product/ProductRegistration.tsx
  open-market/src/tests/setup.ts
  open-market/src/tests/utils/uploadFile.test.ts
Labels: 검토 요청 (이상 없으면 Merge)

#384 ♻️[Refactor] reply 관련 api react-query로 수정 #376
  open-market/src/apis/product/bookmark.ts
  open-market/src/apis/product/detail.ts
  open-market/src/apis/product/replies.ts
  open-market/src/apis/user/replies.ts
  open-market/src/components/SkeletonUI.tsx
  open-market/src/hooks/product/queries/bookmark.ts
  open-market/src/hooks/product/queries/reply.ts
  open-market/src/hooks/reply/mutations/usePostReplyMutation.ts
  open-market/src/hooks/user/queries/replies.ts
  open-market/src/interfaces/product.d.ts
  open-market/src/pages/product/ProductDetail.tsx
  open-market/src/pages/user/MyPage.tsx
  open-market/src/pages/user/UserReplies.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#385 🐛 [Fix] optimistic query를 사용하여 defaultValue로 인한 데이터 업데이트 버그 수정 #383
  open-market/src/hooks/product/mutations/edit.ts
  open-market/src/hooks/user/queries/detail.ts
  open-market/src/pages/product/ProductDetail.tsx
  open-market/src/pages/product/ProductEdit.tsx
Labels: bug fix

#386 ♻️ [Refactor] 마이페이지 관련 api react-query로 수정 및 마이페이지 스켈레톤 ui 수정 #381
  open-market/src/apis/user/bookmarks.ts
  open-market/src/apis/user/orders.ts
  open-market/src/apis/user/products.ts
  open-market/src/apis/user/user.ts
  open-market/src/components/SkeletonUI.tsx
  open-market/src/hooks/user/mutations/bookmark.ts
  open-market/src/hooks/user/queries/bookmarks.ts
  open-market/src/hooks/user/queries/orders.ts
  open-market/src/hooks/user/queries/products.ts
  open-market/src/hooks/user/queries/user.ts
  open-market/src/pages/user/MyPage.tsx
  open-market/src/pages/user/UserBookmarks.tsx
  open-market/src/pages/user/UserOrders.tsx
  open-market/src/pages/user/UserProducts.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#388 ♻️ [Refactor] 상품 구매 관련 api react-query로 수정 #382
  open-market/src/apis/product/order.ts
  open-market/src/hooks/product/mutations/order.ts
  open-market/src/pages/product/ProductPurchase.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#390 ♻️ [Refactor] 로그인 / 회원가입 / 회원정보 수정 페이지 api react-query로 변경 #379
  open-market/src/apis/user/auth.ts
  open-market/src/components/AuthInput.tsx
  open-market/src/hooks/user/queries/useSignInMutation.ts
  open-market/src/hooks/user/queries/useSignUpMutation.ts
  open-market/src/hooks/user/queries/useUpdateUserMutation.ts
  open-market/src/interfaces/signUp.d.ts
  open-market/src/interfaces/user.d.ts
  open-market/src/pages/user/SignIn.tsx
  open-market/src/pages/user/SignUp.tsx
  open-market/src/pages/user/UserEdit.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#391 ♻️ [Refactor] 상품 상세 정보에서 북마크 기능 리액트 쿼리로 변경
  open-market/src/apis/product/bookmark.ts
  open-market/src/apis/user/bookmarks.ts
  open-market/src/components/ProductDetailBadgeComponent.tsx
  open-market/src/hooks/product/queries/bookmark.ts
  open-market/src/hooks/user/mutations/bookmark.ts
  open-market/src/interfaces/product.d.ts
  open-market/src/pages/product/ProductDetail.tsx
  open-market/src/pages/user/UserBookmarks.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#394 ✅ [Test] 상품등록 및 수정 테스트 코드 작성 #368
  open-market/package-lock.json
  open-market/package.json
  open-market/src/pages/product/ProductRegistration.tsx
  open-market/src/tests/Wrapper.tsx
  open-market/src/tests/apis/product/patchProductDetail.test.ts
  open-market/src/tests/apis/product/postProductDetail.test.ts
  open-market/src/tests/hooks/product/mutations/edit.test.ts
  open-market/src/tests/hooks/product/mutations/registration.test.ts
  open-market/src/tests/setup.ts
  open-market/tsconfig.json
Labels: merge 요청, 검토 요청 (이상 없으면 Merge)

#395 ✅ [Test] 댓글 테스트 코드 작성 #373
  open-market/src/apis/product/order.ts
  open-market/src/apis/product/product.ts
  open-market/src/apis/product/replies.ts
  open-market/src/apis/user/replies.ts
  open-market/src/hooks/product/queries/reply.ts
  open-market/src/hooks/reply/mutations/usePostReplyMutation.ts
  open-market/src/pages/product/ProductDetail.tsx
  open-market/src/tests/Counter.test.tsx
  open-market/src/tests/Counter.tsx
  open-market/src/tests/apis/order/getProductOrder.test.ts
  open-market/src/tests/apis/product/getProductDetail.test.ts
  open-market/src/tests/apis/reply/getProductReplies.test.ts
  open-market/src/tests/apis/reply/getUserReplies.test.ts
  open-market/src/tests/apis/reply/postProductReplies.test.ts
  open-market/src/tests/hooks/reply/mutations/post.test.ts
  open-market/tsconfig.json
Labels: 검토 요청 (이상 없으면 Merge)

#398 ✅ [Test] bookmark 테스트 코드 작성 #361
  open-market/src/apis/bookmark/delete.ts
  open-market/src/apis/bookmark/get.ts
  open-market/src/apis/bookmark/post.ts
  open-market/src/hooks/bookmark/queries/useBookMarksSuspenseQuery.ts
  open-market/src/tests/apis/bookmark/deleteUserBookmark.test.ts
  open-market/src/tests/apis/bookmark/getProductBookmark.test.ts
  open-market/src/tests/apis/bookmark/getUserBookmarks.test.ts
  open-market/src/tests/apis/bookmark/postUserBookmark.test.ts
  open-market/src/tests/hooks/bookmark/queries/get.test.ts
Labels: merge 요청, 검토 요청 (이상 없으면 Merge)
