Repository techitPlus-FE-team3/open_market_projerct, pull requests merged in 2024-04, with the labels that each got.

#306 :bug: [Fix] 페이지 이동 시 스크롤이 최상딘에 위치하지 않는 버그 수정 #305
  open-market/src/App.tsx
  open-market/src/components/ScrollToTop.tsx
  open-market/src/main.tsx
  open-market/src/routes.tsx
Labels: bug fix

#309 🐛 [Fix] 뮤직 플레이어 동작 오류 #304
  open-market/src/components/listMusicPlayer/MusicPlayer.tsx
Labels: bug, bug fix

#310 🐛[Fix] 액세스 토큰 만료시 토큰 갱신 요청이 중복해서 발생하는 문제 해결 #271
  open-market/src/utils/refreshToken.ts
Labels: 검토 요청 (이상 없으면 Merge), bug fix

#312 ✨[Feat] 음원 중복 재생 방지 기능 구현 #311
  open-market/src/components/ProductListComponent.tsx
  open-market/src/components/listMusicPlayer/MusicPlayer.tsx
  open-market/src/pages/Index.tsx
  open-market/src/pages/user/UserOrders.tsx
  open-market/src/pages/user/UserProducts.tsx
  open-market/src/states/audioPlayerState.ts
Labels: 검토 요청 (이상 없으면 Merge)

#320 💄[Design] 특정 페이지에서의 body영역 정렬 스타일링 이슈 #317
  open-market/src/styles/ProductListStyle.tsx
Labels: 검토 요청 (이상 없으면 Merge), bug fix

#322 💄[Design] 헤더 알림 버튼 제거 #318
  open-market/src/layout/Header.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#323 ♻️[Refactor] MusicPlayerSlider 컴포넌트 리팩토링 #321
  open-market/src/components/ProductDetailComponent.tsx
  open-market/src/components/audioPlayer/MusicPlayer.tsx
  open-market/src/components/audioPlayer/PlayerSlider.tsx
Labels: 검토 요청 (이상 없으면 Merge), non-critical

#325 ✨ [Feat] 디테일 페이지 댓글 컴포넌트 무한 스크롤 구현 #324
  open-market/src/components/ReplyComponent.tsx
  open-market/src/pages/Index.tsx
  open-market/src/pages/product/ProductDetail.tsx
  open-market/src/pages/user/UserOrders.tsx
  open-market/src/pages/user/UserProducts.tsx
  open-market/src/styles/ProductListStyle.tsx
Labels: 검토 요청 (이상 없으면 Merge), non-critical

#327 :sparkles: [Feat] 북마크 기능 추가 #315
  open-market/src/App.tsx
  open-market/src/components/ProductListComponent.tsx
  open-market/src/pages/Index.tsx
  open-market/src/pages/user/MyPage.tsx
  open-market/src/pages/user/UserBookmarks.tsx
Labels: merge 요청, 검토 요청 (이상 없으면 Merge)

#330 ✨ [Feat] 리액트 헬멧 활용 메타 태그, 오픈 그래프 개선 #319
  open-market/src/components/HelmetSetup.tsx
  open-market/src/pages/Index.tsx
  open-market/src/pages/product/ProductDetail.tsx
  open-market/src/pages/product/ProductEdit.tsx
  open-market/src/pages/product/ProductManage.tsx
  open-market/src/pages/product/ProductPurchase.tsx
  open-market/src/pages/product/ProductRegistration.tsx
  open-market/src/pages/user/MyPage.tsx
  open-market/src/pages/user/SignIn.tsx
  open-market/src/pages/user/SignUp.tsx
  open-market/src/pages/user/UserEdit.tsx
  open-market/src/pages/user/UserOrders.tsx
  open-market/src/pages/user/UserProducts.tsx
Labels: 검토 요청 (이상 없으면 Merge), 검토중

#332 🐛 [Fix] 마이페이지 기존 helmet import 제거 #319
  open-market/src/pages/user/MyPage.tsx
Labels: merge 요청, bug fix

#336 ✨[Feat] 내가 쓴 댓글 모아보는 기능 구현 #326
  open-market/src/App.tsx
  open-market/src/components/ProductListComponent.tsx
  open-market/src/interfaces/product.d.ts
  open-market/src/pages/user/MyPage.tsx
  open-market/src/pages/user/UserReplies.tsx
Labels: 검토 요청 (이상 없으면 Merge), non-critical

#343 isNew, isBest sort 기능 구현 #337
  open-market/src/components/FilterComponent.tsx
  open-market/src/components/SearchBar.tsx
  open-market/src/pages/Index.tsx
  open-market/src/pages/user/UserOrders.tsx
  open-market/src/pages/user/UserProducts.tsx
  open-market/src/utils/index.ts
  open-market/src/utils/sortProductList.ts
Labels: 검토 요청 (이상 없으면 Merge), non-critical

#341 ✨ [Feat] 접근성 기능 향상 (이미지 대체 텍스트) #338
  open-market/public/videos/mainVideo.vtt
  open-market/src/components/ProductListComponent.tsx
  open-market/src/components/SearchBar.tsx
  open-market/src/layout/Header.tsx
  open-market/src/pages/Index.tsx
  open-market/src/pages/product/ProductManage.tsx
  open-market/src/pages/product/ProductPurchase.tsx
  open-market/src/pages/user/MyPage.tsx
  open-market/src/pages/user/SignIn.tsx
  open-market/src/pages/user/SignUp.tsx
  open-market/src/pages/user/UserBookmarks.tsx
  open-market/src/pages/user/UserEdit.tsx
  open-market/src/utils/refreshToken.ts
Labels: 검토 요청 (이상 없으면 Merge)

#345 ✨ [Feat] 접근성 기능 향상(버튼과 입력 필드) #342
  open-market/src/components/MyPageList.tsx
  open-market/src/components/ProductDetailBadgeComponent.tsx
  open-market/src/components/ProductDetailComponent.tsx
  open-market/src/components/ProductListComponent.tsx
  open-market/src/components/ReplyComponent.tsx
  open-market/src/components/SearchBar.tsx
  open-market/src/components/audioPlayer/ControlPanel.tsx
  open-market/src/components/audioPlayer/MusicPlayer.tsx
  open-market/src/layout/Header.tsx
  open-market/src/pages/Index.tsx
  open-market/src/pages/product/ProductDetail.tsx
  open-market/src/pages/product/ProductEdit.tsx
  open-market/src/pages/product/ProductManage.tsx
  open-market/src/pages/product/ProductPurchase.tsx
  open-market/src/pages/product/ProductRegistration.tsx
  open-market/src/pages/user/MyPage.tsx
  open-market/src/pages/user/SignUp.tsx
  open-market/src/pages/user/UserBookmarks.tsx
  open-market/src/pages/user/UserEdit.tsx
  open-market/src/pages/user/UserOrders.tsx
  open-market/src/pages/user/UserProducts.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#348 💄 [Design] 리스트 컨테이너 통일 작업 / 아이콘 색상 변경 및 크기 조정 #347
  open-market/src/components/Textarea.tsx
  open-market/src/pages/user/MyPage.tsx
  open-market/src/pages/user/UserBookmarks.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#353 ♻️ [Refactor] 디테일 페이지 UI 세부 조정 #344
  open-market/src/components/ProductDetailComponent.tsx
  open-market/src/pages/product/ProductEdit.tsx
Labels: 검토 요청 (이상 없으면 Merge), non-critical

#355 💄[Design] 헤더 드롭다운 제거 및 구조 변경 #349
  open-market/package-lock.json
  open-market/package.json
  open-market/src/layout/Header.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#352 💄[Design] 마이페이지 회원정보, 내가 쓴 댓글 영역 레이웃 수정 #350
  open-market/src/pages/user/MyPage.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#360 📦 [Chore] 테스트코드 작성을 위한 환경 세팅 #359
  open-market/package-lock.json
  open-market/package.json
  open-market/src/tests/Counter.test.tsx
  open-market/src/tests/Counter.tsx
  open-market/src/tests/setup.ts
  open-market/vite.config.ts
Labels: 검토 요청 (이상 없으면 Merge), non-critical

#363 ♻️ [Refactor] 상품 리스트 컴포넌트 리팩토링 #358
  open-market/src/components/ProductDetailBadgeComponent.tsx
  open-market/src/components/ProductListComponent.tsx
  open-market/src/components/SkeletonUI.tsx
  open-market/src/components/audioPlayer/MusicPlayer.tsx
  open-market/src/interfaces/product.d.ts
  open-market/src/pages/Index.tsx
  open-market/src/pages/user/UserOrders.tsx
Labels: 검토 요청 (이상 없으면 Merge), non-critical

#364 💄[Design] 앨범 아트 호출 실패시 대체 이미지 표시 기능 추가 #351
  open-market/public/alt_cover.png
  open-market/src/components/MyPageList.tsx
  open-market/src/pages/product/ProductRegistration.tsx
  open-market/src/pages/user/MyPage.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#365 🐛 [Fix] 404페이지 작동 문제 #290 #329
  open-market/src/App.tsx
  open-market/src/pages/error/ErrorBoundary.tsx
Labels: 검토 요청 (이상 없으면 Merge), bug fix

#369 💄[Design] 앨범 아트 호출 실패시 대체 이미지 표시 기능 추가 #351
  open-market/src/components/ProductDetailComponent.tsx
  open-market/src/components/ProductListComponent.tsx
Labels: 검토 요청 (이상 없으면 Merge)

#374 ✅ [Test] 로그인/로그아웃 컴포넌트 테스트 코드 작성 #371
  open-market/package-lock.json
  open-market/package.json
  open-market/src/layout/Header.tsx
  open-market/src/pages/user/SignIn.tsx
  open-market/src/tests/Header.test.tsx
  open-market/src/tests/SignIn.api.test.tsx
  open-market/src/tests/SignIn.render.test.tsx
Labels: 검토 요청 (이상 없으면 Merge)
